#!/bin/bash

playerctl --follow metadata --format \
'{{title}}\{{artist}}\{{album}}\{{playerName}}\{{status}}\{{mpris:artUrl}}\{{duration(position)}}\{{duration(mpris:length)}}\{{shuffle}}\{{loop}}\{{position}}\{{mpris:length}}' |

while IFS=$'\\' read -r title artist album player status artUrl position length shuffle loop p l; do

  p=${p%??????}
  l=${l%??????}

  title=${title//\"/\\\"}
  artist=${artist//\"/\\\"}
  album=${album//\"/\\\"}

  echo '{"title": "'$title'", "artist": "'$artist'", "album": "'$album'", "player": "'$player'", "status": "'$status'", "artUrl": "'$artUrl'", "position": "'$position'", "length": "'$length'", "shuffle": "'$shuffle'", "loop": "'$loop'", "p": "'$p'", "l": "'$l'"}'
done